version: '3'
services:
  ganache:
    image: trufflesuite/ganache:latest
    ports:
      - 8545:8545
    networks:
      backend:
        ipv4_address: 172.15.0.3
    entrypoint: ["node","/app/dist/node/cli.js","--database.dbPath", "./ganache_cache","--chain.chainId","0x2324","--chain.networkId","0x2324","-l","10000000000","-g","1","--chain.hardfork","${GANACHE_FORK}","--miner.blockTime","${GANACHE_BLOCKTIME}","--miner.instamine","${GANACHE_INSTAMINE}","--wallet.mnemonic","${GANACHE_MNEMONIC}", "-e","1000000"]
