version: "3"
services:
  pdr-predictoor1:
    image: oceanprotocol/pdr-backend:${PDR_BACKEND_VERSION:-latest}
    command: predictoor 1 ppss.yaml development
    networks:
      backend:
        ipv4_address: 172.15.0.41
    environment:
      PRIVATE_KEY: "0xef4b441145c1d0f3b4bc6d61d29f5c6e502359481152f869247c7a4244d45209"
      WAIT_FOR_SUBGRAPH: "true"
      DELAYED_STARTUP: 120
    depends_on:
      - ganache
    volumes:
      - ${OCEAN_ARTIFACTS_FOLDER}:/ocean-contracts/artifacts/
      - ${OCEAN_SUBGRAPH_FOLDER}:/ocean-subgraph/
  pdr-predictoor2:
    image: oceanprotocol/pdr-backend:${PDR_BACKEND_VERSION:-latest}
    command: predictoor 3 ppss.yaml development
    networks:
      backend:
        ipv4_address: 172.15.0.45
    environment:
      WAIT_FOR_SUBGRAPH: "true"
      DELAYED_STARTUP: 120
    depends_on:
      - ganache
    volumes:
      - ${OCEAN_ARTIFACTS_FOLDER}:/ocean-contracts/artifacts/
      - ${OCEAN_SUBGRAPH_FOLDER}:/ocean-subgraph/
  pdr-predictoor3:
    image: oceanprotocol/pdr-backend:${PDR_BACKEND_VERSION:-latest}
    command: predictoor
    networks:
      backend:
        ipv4_address: 172.15.0.46
    environment:
      PRIVATE_KEY: "0xa50c16d96ed01ac8f967b77b01b1fa94f751c4c600b564fd770e239ebd7d869d"
      WAIT_FOR_SUBGRAPH: "true"
      DELAYED_STARTUP: 120
    depends_on:
      - ganache
    volumes:
      - ${OCEAN_ARTIFACTS_FOLDER}:/ocean-contracts/artifacts/
      - ${OCEAN_SUBGRAPH_FOLDER}:/ocean-subgraph/
