version: "3"
services:
  pdr-trader:
    image: oceanprotocol/pdr-backend:${PDR_BACKEND_VERSION:-latest}
    command: trader 1 ppss.yaml development
    networks:
      backend:
        ipv4_address: 172.15.0.42
    environment:
      PRIVATE_KEY: "0x8467415bb2ba7c91084d932276214b11a3dd9bdb2930fefa194b666dd8020b99"
      WAIT_FOR_SUBGRAPH: "true"
      DELAYED_STARTUP: 120
    depends_on:
      - ganache
    volumes:
      - ${OCEAN_ARTIFACTS_FOLDER}:/ocean-contracts/artifacts/
      - ${OCEAN_SUBGRAPH_FOLDER}:/ocean-subgraph/
