version: '3'
services:
  pdr-trader:
    image: oceanprotocol/pdr-trader:${PDR_TRADER_VERSION:-latest}
    networks:
      backend:
        ipv4_address: 172.15.0.42
    environment:
      RPC_URL: ${NETWORK_RPC_URL}
      SUBGRAPH_URL: http://172.15.0.15:8000/subgraphs/name/oceanprotocol/ocean-subgraph
      PRIVATE_KEY: "0x8467415bb2ba7c91084d932276214b11a3dd9bdb2930fefa194b666dd8020b99"
      WAIT_FOR_SUBGRAPH: "true"
      DELAYED_STARTUP: 120
    depends_on:
      - ganache
    volumes:
    - ${OCEAN_ARTIFACTS_FOLDER}:/ocean-contracts/artifacts/
    - ${OCEAN_SUBGRAPH_FOLDER}:/ocean-subgraph/
